# Uncomment this if your project is hosted on GitHub:
github_url = "https://github.com/umonaca/bestlab_platform/"

[version]
current = "0.2.2"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "release: bump to {new_version}"
tag_template = "{new_version}"

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[file]]
src = "bestlab_platform/__init__.py"

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made

#  [[before_commit]]
#  name = "check changelog"
#  cmd = "grep -q {new_version} Changelog.rst"

# Or run some commands after the git tag and the branch
# have been pushed:
[[after_push]]
name = "publish"
cmd = "flit build & flit publish"
